### ISSUE TITLE
can't install mutationpp in python

### ISSUE THREAD

**Issue by Ying-Zi66** [mutationpp/Mutationpp#276]
**My OS is Windows11: 

 
**Cmake Version:3.31.0

I want to install mutationpp in python3, use command ‘pip install mutationpp’，it don't work
It shows:
(base) PS C:\Users\yingzi\Downloads> pip install mutationpp-1.0.6.dev38.tar.gz
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing c:\users\yingzi\downloads\mutationpp-1.0.6.dev38.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: mutationpp
  Building wheel for mutationpp (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for mutationpp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [868 lines of output]

      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v144)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      -- The C compiler identification is IntelLLVM 2024.1.0 with MSVC-like command-line
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: C:/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/icx.exe
      -- Check for working C compiler: C:/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/icx.exe - broken
      CMake Error at C:/Users/yingzi/AppData/Local/Temp/pip-build-env-gci3pngh/overlay/Lib/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

          "C:/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/icx.exe"

        is not able to compile a simple test program.

        It fails with the following output:

          Change Dir: 'C:/Users/yingzi/AppData/Local/Temp/pip-req-build-iceyyh7s/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-cz0f7l'

          Run Build Command(s): C:/Users/yingzi/AppData/Local/Temp/pip-build-env-gci3pngh/overlay/Lib/site-packages/ninja/data/bin/ninja -v cmTC_79215
          [1/2] C:\PROGRA~2\Intel\oneAPI\compiler\latest\bin\icx.exe  /nologo   /DWIN32 /D_WINDOWS /W3  /MDd /Zi /Ob0 /Od /RTC1 -QMD -QMT CMakeFiles\cmTC_79215.dir\testCCompiler.c.obj -QMF CMakeFiles\cmTC_79215.dir\testCCompiler.c.obj.d /FoCMakeFiles\cmTC_79215.dir\testCCompiler.c.obj /FdCMakeFiles\cmTC_79215.dir\ -c C:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\_cmake_test_compile\build\CMakeFiles\CMakeScratch\TryCompile-cz0f7l\testCCompiler.c
          [2/2] C:\Windows\system32\cmd.exe /C "cd . && C:\Users\yingzi\AppData\Local\Temp\pip-build-env-gci3pngh\overlay\Lib\site-packages\cmake\data\bin\cmake.exe -E vs_link_exe --msvc-ver=1939 --intdir=CMakeFiles\cmTC_79215.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x86\mt.exe --manifests  -- C:\PROGRA~2\Intel\oneAPI\compiler\latest\bin\icx.exe /nologo CMakeFiles\cmTC_79215.dir\testCCompiler.c.obj  /Qoption,link,/machine:x64  /Qoption,link,/debug /Qoption,link,/INCREMENTAL /Qoption,link,/subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /link /out:cmTC_79215.exe /implib:cmTC_79215.lib /pdb:cmTC_79215.pdb /version:0.0 && cd ."
          FAILED: cmTC_79215.exe
          C:\Windows\system32\cmd.exe /C "cd . && C:\Users\yingzi\AppData\Local\Temp\pip-build-env-gci3pngh\overlay\Lib\site-packages\cmake\data\bin\cmake.exe -E vs_link_exe --msvc-ver=1939 --intdir=CMakeFiles\cmTC_79215.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x86\mt.exe --manifests  -- C:\PROGRA~2\Intel\oneAPI\compiler\latest\bin\icx.exe /nologo CMakeFiles\cmTC_79215.dir\testCCompiler.c.obj  /Qoption,link,/machine:x64  /Qoption,link,/debug /Qoption,link,/INCREMENTAL /Qoption,link,/subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /link /out:cmTC_79215.exe /implib:cmTC_79215.lib /pdb:cmTC_79215.pdb /version:0.0 && cd ."
          LINK: command "C:\PROGRA~2\Intel\oneAPI\compiler\latest\bin\icx.exe /nologo CMakeFiles\cmTC_79215.dir\testCCompiler.c.obj /Qoption,link,/machine:x64 /Qoption,link,/debug /Qoption,link,/INCREMENTAL /Qoption,link,/subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /link /out:cmTC_79215.exe /implib:cmTC_79215.lib /pdb:cmTC_79215.pdb /version:0.0 /MANIFEST:EMBED,ID=1" failed (exit code 1104) with the following output:
          LINK : fatal error LNK1104: 鏃犳硶鎵撳紑鏂囦欢鈥渕svcrtd.lib鈥\x9d

          icx: error: linker command failed with exit code 1104 (use -v to see invocation)

          ninja: build stopped: subcommand failed.

        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (ENABLE_LANGUAGE)

      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v144)' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v144' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Failed to run MSBuild command:

          C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe

        to get the value of VCTargetsPath:

          閫傜敤浜\x8e .NET Framework MSBuild 鐗堟湰 17.9.8+b34f75857
          鐢熸垚鍚\xaf鍔ㄦ椂闂翠负 2024/11/20 20:34:04銆\x82

          鑺傜偣 1 涓婄殑椤圭洰鈥淐:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\_cmake_test_compile\build\CMakeFiles\3.31.0\VCTargetsPath.vcxproj鈥\x9d(榛樿\xaeょ洰鏍\x87)銆\x82
          C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: 鏃犳硶鎵惧埌 v144 鐨勭敓鎴愬伐鍏\xb7(骞冲彴宸ュ叿闆\x86 =鈥渧144鈥\x9d)銆傝嫢瑕佷娇鐢\xa8 v144 鐢 熸垚宸ュ叿杩涜\xa1岀敓鎴愶紝璇峰畨瑁\x85 v144 鐢熸垚宸ュ叿銆傛垨鑰咃紝鍙\xaf浠ュ崌绾у埌褰撳墠 Visual Studio 宸ュ叿锛屾柟寮忔槸閫氳繃閫夋嫨鈥滈」鐩\xae鈥濊彍鍗曟垨鍙抽敭鍗曞嚮璇ヨВ鍐虫柟妗堬紝鐒跺悗閫夋嫨鈥滈噸瀹氳В鍐虫柟妗堢洰鏍団\x80濄\x80\x82 [C:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\_cmake_test_compile\build\CMakeFiles\3.31.0\VCTargetsPath.vcxproj]
          宸插畬鎴愮敓鎴愰」鐩\xae鈥淐:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\_cmake_test_compile\build\CMakeFiles\3.31.0\VCTargetsPath.vcxproj鈥\x9d(榛樿\xaeょ洰鏍\x87)鐨勬搷浣\x9c - 澶辫触銆\x82

          鐢熸垚澶辫触銆\x82

          鈥淐:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\_cmake_test_compile\build\CMakeFiles\3.31.0\VCTargetsPath.vcxproj鈥\x9d(榛樿\xaeょ洰鏍\x87) (1) ->
          (PrepareForBuild 鐩\xae鏍\x87) ->
            C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: 鏃犳硶鎵惧埌 v144 鐨勭敓鎴愬伐鍏\xb7(骞冲彴宸ュ叿闆\x86 =鈥渧144鈥\x9d)銆傝嫢瑕佷娇鐢\xa8 v144  鐢熸垚宸ュ叿杩涜\xa1岀敓鎴愶紝璇峰畨瑁\x85 v144 鐢熸垚宸ュ叿銆傛垨鑰咃紝鍙\xaf浠ュ崌绾у埌褰撳墠 Visual Studio 宸ュ叿锛屾柟寮忔槸閫氳繃閫夋嫨鈥滈」鐩\xae鈥濊彍鍗曟垨鍙抽敭鍗曞嚮璇ヨВ鍐虫柟妗堬紝鐒跺悗閫夋嫨鈥滈噸瀹氳В鍐虫柟妗堢洰鏍団\x80濄\x80\x82 [C:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\_cmake_test_compile\build\CMakeFiles\3.31.0\VCTargetsPath.vcxproj]

              0 涓\xaa璀﹀憡
              1 涓\xaa閿欒\xaf\xaf

          宸茬敤鏃堕棿 00:00:00.25

        Exit code: 1

      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v144' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      -- The C compiler identification is MSVC 19.39.33523.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.39.33523.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (6.1s)
      -- Generating done (0.2s)
      -- Build files have been written to: C:/Users/yingzi/AppData/Local/Temp/pip-req-build-iceyyh7s/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\_skbuild\win-amd64-3.10\cmake-build
        Command:
          'C:\Users\yingzi\AppData\Local\Temp\pip-build-env-gci3pngh\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s' -G Ninja '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\yingzi\AppData\Local\Temp\pip-build-env-gci3pngh\overlay\Lib\site-packages\ninja\data\bin\ninja' -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\_skbuild\win-amd64-3.10\cmake-install\interface\python\mutationpp' -DPYTHON_VERSION_STRING:STRING=3.10.14 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\yingzi\AppData\Local\Temp\pip-build-env-gci3pngh\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\ProgramData\anaconda3\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\ProgramData\anaconda3\Include' '-DPYTHON_LIBRARY:PATH=C:\ProgramData\anaconda3\libs\python310.lib' '-DPython_EXECUTABLE:PATH=C:\ProgramData\anaconda3\python.exe' '-DPython_ROOT_DIR:PATH=C:\ProgramData\anaconda3' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\ProgramData\anaconda3\Include' '-DPython_LIBRARY:PATH=C:\ProgramData\anaconda3\libs\python310.lib' '-DPython3_EXECUTABLE:PATH=C:\ProgramData\anaconda3\python.exe' '-DPython3_ROOT_DIR:PATH=C:\ProgramData\anaconda3' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\ProgramData\anaconda3\Include' '-DPython3_LIBRARY:PATH=C:\ProgramData\anaconda3\libs\python310.lib' '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\yingzi\AppData\Local\Temp\pip-build-env-gci3pngh\overlay\Lib\site-packages\ninja\data\bin\ninja' -DMUTATIONPP_VERSION_FROM_PYTHON=1.0.6 -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      CMake Deprecation Warning at CMakeLists.txt:30 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      -- The CXX compiler identification is MSVC 19.39.33523.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Deprecation Warning at thirdparty/pybind11/CMakeLists.txt:8 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      -- pybind11 v2.6.2
      CMake Warning (dev) at thirdparty/pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.

      Call Stack (most recent call first):
        thirdparty/pybind11/tools/pybind11Tools.cmake:45 (find_package)
        thirdparty/pybind11/tools/pybind11Common.cmake:201 (include)
        thirdparty/pybind11/CMakeLists.txt:188 (include)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Found PythonInterp: C:/ProgramData/anaconda3/python.exe (found version "3.10.14")
      -- Found PythonLibs: C:/ProgramData/anaconda3/libs/python310.lib
      -- Performing Test HAS_MSVC_GL_LTCG
      -- Performing Test HAS_MSVC_GL_LTCG - Success
      -- Searching for Eigen3...
      -- Found Eigen3: C:/Users/yingzi/AppData/Local/Temp/pip-req-build-iceyyh7s/thirdparty/eigen
      -- Configuring done (5.5s)
      -- Generating done (0.4s)
      -- Build files have been written to: C:/Users/yingzi/AppData/Local/Temp/pip-req-build-iceyyh7s/_skbuild/win-amd64-3.10/cmake-build
      [1/80] Building CXX object src\CMakeFiles\mutation++.dir\kinetics\ReactionType.cpp.obj
      [2/80] Building CXX object src\CMakeFiles\mutation++.dir\kinetics\StoichiometryManager.cpp.obj
      [3/80] Building CXX object src\CMakeFiles\mutation++.dir\thermo\SpeciesNameFSM.cpp.obj
      [4/80] Building CXX object src\CMakeFiles\mutation++.dir\thermo\Composition.cpp.obj
      C:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\src\thermo\Composition.h(81): warning C4267: “return”:  从“size_t”转换到“int”，可能丢失数据
      [5/80] Building CXX object interface\python\CMakeFiles\_mutationpp.dir\src\mutationpp_python.cpp.obj
      [6/80] Building CXX object interface\python\CMakeFiles\_mutationpp.dir\src\pyMixtureOptions.cpp.obj
      C:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\src\thermo\Composition.h(81): warning C4267: “return”:  从“size_t”转换到“int”，可能丢失数据
      [7/80] Building CXX object src\CMakeFiles\mutation++.dir\kinetics\Reaction.cpp.obj
      FAILED: src/CMakeFiles/mutation++.dir/kinetics/Reaction.cpp.obj
      C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1439~1.335\bin\Hostx86\x64\cl.exe  /nologo /TP  -IC:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\src\general -IC:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\src\kinetics -IC:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\src\numerics -
.........
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\Users\yingzi\AppData\Local\Temp\pip-build-env-gci3pngh\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 668, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "C:\Users\yingzi\AppData\Local\Temp\pip-build-env-gci3pngh\overlay\Lib\site-packages\skbuild\cmaker.py", line 696, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "C:\Users\yingzi\AppData\Local\Temp\pip-build-env-gci3pngh\overlay\Lib\site-packages\skbuild\cmaker.py", line 741, in make_impl
          raise SKBuildError(msg)

      An error occurred while building with CMake.
        Command:
          'C:\Users\yingzi\AppData\Local\Temp\pip-build-env-gci3pngh\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' --build . --target install --config Release --
        Install target:
          install
        Source directory:
          C:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s
        Working directory:
          C:\Users\yingzi\AppData\Local\Temp\pip-req-build-iceyyh7s\_skbuild\win-amd64-3.10\cmake-build
      Please check the install target is valid and see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mutationpp
Failed to build mutationpp
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (mutationpp)

**Comments**

**Comment by jbscoggi** [comment]
Hi @Ying-Zi66, please try updating pybind11 and try again:

```bash
cd thirdpary/pybind11
git pull origin master
```
